<a href="https://colab.research.google.com/github/athulkrishna174/Learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [20]:
#please provide your answer below this line.
import numpy as np
matrix_1 = np.random.randint(10, size = (3, 3))
print("Matrix 1\n", matrix_1)
matrix_2 = np.random.randint(10, size = (3, 3))
print("Matrix 2\n", matrix_2)
product = matrix_1.dot(matrix_2)
print("Dot Proudct\n", product)
print("Transpose\n", product.transpose())

Matrix 1
 [[8 1 3]
 [2 4 8]
 [3 8 1]]
Matrix 2
 [[6 4 4]
 [5 1 0]
 [1 1 7]]
Dot Proudct
 [[56 36 53]
 [40 20 64]
 [59 21 19]]
Transpose
 [[56 40 59]
 [36 20 21]
 [53 64 19]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [19]:
#please provide your answer below this line.
import numpy as np
matrix = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Matrix\n", matrix)
print("Determinant\n", int(np.linalg.det(matrix)))

Matrix
 [[55 25 15]
 [30 44  2]
 [11 45 77]]
Determinant
 137180
