<a href="https://colab.research.google.com/github/athulkrishna174/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [2]:
#please provide your answer below this line.
import numpy as np
np.random.rand(3, 3)

array([[0.62490667, 0.69327733, 0.91889661],
       [0.82392698, 0.15243892, 0.59668588],
       [0.59920081, 0.02603598, 0.47069028]])

2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [15]:
#please provide your answer below this line.
import numpy as np
arr_1 = np.random.randint(100, size=(4, 4))
print("Array 1\n", arr_1)
arr_2 = np.random.randint(50, size=(4, 4))
print("Array 2\n", arr_2)
reshaped_arr_1 = arr_1.reshape(2,8)
reshaped_arr_2 = arr_2.reshape(2,8)
print("Reshaped Array 1\n", reshaped_arr_1, "\nReshaped Array 2\n", reshaped_arr_2)
print("Vertical Stack")
print(np.vstack((reshaped_arr_1,reshaped_arr_2)))
print("Horizontal Stack")
print(np.hstack((reshaped_arr_1,reshaped_arr_2)))

Array 1
 [[68 16 75 73]
 [91 21 50 22]
 [82 33  4 62]
 [21 41 75 91]]
Array 2
 [[18  7 41 22]
 [33 49 18 34]
 [48 19 39 23]
 [35  6 32  2]]
Reshaped Array 1
 [[68 16 75 73 91 21 50 22]
 [82 33  4 62 21 41 75 91]] 
Reshaped Array 2
 [[18  7 41 22 33 49 18 34]
 [48 19 39 23 35  6 32  2]]
Vertical Stack
[[68 16 75 73 91 21 50 22]
 [82 33  4 62 21 41 75 91]
 [18  7 41 22 33 49 18 34]
 [48 19 39 23 35  6 32  2]]
Horizontal Stack
[[68 16 75 73 91 21 50 22 18  7 41 22 33 49 18 34]
 [82 33  4 62 21 41 75 91 48 19 39 23 35  6 32  2]]
