<a href="https://colab.research.google.com/github/athulkrishna174/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [18]:
#please provide your answer below this line.
import numpy as np
np.random.rand(3, 3)

array([[0.89367832, 0.08598069, 0.82189166],
       [0.3891278 , 0.14677861, 0.09080971],
       [0.48099305, 0.88382961, 0.80694361]])

2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [36]:
#please provide your answer below this line.
import numpy as np
arr = np.random.randint(100, size=(4, 4))
print("Array\n", arr)
reshaped_arr = arr.reshape(2,8)
print("Reshaped Array\n", reshaped_arr)
print("Vertical Stack")
print(np.vstack(reshaped_arr))
print("Horizontal Stack")
print(np.hstack(reshaped_arr))

Array
 [[71 27 27 42]
 [12 25 42 14]
 [30 53 96 68]
 [18 37 68 44]]
Reshaped Array
 [[71 27 27 42 12 25 42 14]
 [30 53 96 68 18 37 68 44]]
Vertical Stack
[[71 27 27 42 12 25 42 14]
 [30 53 96 68 18 37 68 44]]
Horizontal Stack
[71 27 27 42 12 25 42 14 30 53 96 68 18 37 68 44]
