<a href="https://colab.research.google.com/github/athulkrishna174/Learn.py/blob/main/TASK_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array containing the values ranging from 0 - 15 (use arange function). Then ,
  
  a) split it equally along horizontal.

  b) split it as 4 parts vertically.



In [34]:
#please provide your answer below this line
import numpy as np
arr = np.arange(0, 16).reshape(4, 4)
print("Array\n", arr)
print("Horizontal Split =", np.hsplit(arr, 4))
print("Vertical Split =", np.vsplit(arr, 4))

Array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizontal Split = [array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
Vertical Split = [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


2. Create a 3x3 matrix using random module and then,

  a) Find the ceil of the matrix.
  
  b) Find the floor of the matrix.

In [25]:
#please provide your answer below this line
import numpy as np
arr = np.random.rand(3, 3)
print("Array\n", arr)
print("Ceil of matrix\n", np.ceil(arr))
print("Floor of matrix\n", np.floor(arr))

Array
 [[0.35046013 0.88115029 0.50827982]
 [0.67816048 0.80870983 0.76336542]
 [0.80546572 0.76371207 0.79960498]]
Ceil of matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Floor of matrix
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a random 1x4 array and print the random array and its shape.
    
      (use the shape function for finding the shape & use the same random we created here for both the below operations.)

  a) Squeeze the random array and print the squeezed array and its shape.
  b) Expand the random array by one axis and print the expanded array and its shape.

In [39]:
#please provide your answer below this line.
arr = np.random.rand(1, 4)
print("Array\n", arr, "Shape =", arr.shape)
print("Squezed Array\n", np.squeeze(arr), "Shape =", np.squeeze(arr).shape)
print("Expanded Array\n", np.expand_dims(arr, axis = 1), "Shape =", np.expand_dims(arr, axis = 1).shape)

Array
 [[0.80055403 0.58399576 0.58599902 0.82790609]] Shape = (1, 4)
Squezed Array
 [0.80055403 0.58399576 0.58599902 0.82790609] Shape = (4,)
Expanded Array
 [[[0.80055403 0.58399576 0.58599902 0.82790609]]] Shape = (1, 1, 4)
