<a href="https://colab.research.google.com/github/athulkrishna174/Learn.py/blob/main/TASK%2012.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [16]:
#please type your answer below this line.
import numpy as np
arr = np.arange(0, 16).reshape(4, 4)
print("Trace of the array =", np.trace(arr))

Trace of the array = 30


2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [15]:
#please type your answer below this line.
import numpy as np
arr = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print("Inverse of the Matrix\n", np.linalg.inv(arr))

Inverse of the Matrix
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [19]:
#please type your answer below this line.
import numpy as np
arr = np.arange(0, 9).reshape(3, 3)
print("Norm of the array =", np.linalg.norm(arr))

Norm of the array = 14.2828568570857


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [25]:
#please type your answer below this line.
import numpy as np
arr = np.arange(0, 16).reshape(4, 4)
result = np.linalg.eig(arr)
print("Eigen values of the array =", result[0])
print("Eigen vectors of the array\n", result[1])

Eigen values of the array = [ 3.24642492e+01 -2.46424920e+00  2.55670932e-15 -1.93389056e-16]
Eigen vectors of the array
 [[-0.11417645  0.7327781  -0.54471271  0.09683789]
 [-0.3300046   0.28974835  0.76902356  0.27269982]
 [-0.54583275 -0.15328139  0.09609099 -0.8359133 ]
 [-0.76166089 -0.59631113 -0.32040185  0.46637559]]
